[server]
runOnSave = true
fileWatcherType = "poll"

[runner]
fastReruns = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#8B0000"
backgroundColor = "#0B0B0B"
secondaryBackgroundColor = "#1F1F1F"
textColor = "#F8F8F8"
font = "sans serif"

[client]
toolbarMode = "minimal"
